### ISSUE TITLE
Robot Vacuum (sd)

### ISSUE THREAD

**Issue by tv4you2016** [rikman122/tuya-vacuum-card#2]
Hi,
it will be possible to add the Vacuum robot
the api is as follows:
https://developer.tuya.com/en/docs/iot/fsd?id=K9gf487ck1tlo

If you can't, could you give me some tips to help with the integration?

**Comment by rikman122** [comment]
Hi,

This card is designed to work with vacuums integrated with LocalTuya project for Home Assistant. The vacuum component in LocalTuya is currently under development so you can't find it in the current release. If you are not experienced with beta testing or debugging I would recommend you to wait until vacuum is officially supported in LocalTuya.

Regards
