### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by igna09** [rikman122/tuya-vacuum-card#3]
I tried to install this card following the guide (moving js library to www folder) and by adding library link (https://raw.githubusercontent.com/rikman122/tuya-vacuum-card/master/tuya-vacuum-card.js) from the gui but when i try to create a custom card hassio says that "custom:tuya-vacuum-card" doesn't exist

**Comment by rikman122** [comment]
You have to add the path to the library from your local file system not the github URL. Or you can add this repository as a custom HACS repository to get updates and forget about manual configuration

**Comment by igna09** [comment]
Thank you for your help, I already tried to add as custom component to hacs but as integration, not as lovelace module, now it is working, thank you
